services:
  fastapi:
    image: dataspace-api-gateway
    build: .
    container_name: "api"
    working_dir: /app/
    volumes:
      - "./app/:/app/"
      - "./.env/:/app/.env"
    command: 'python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000'
    restart: always
    ports:
      - 8000:8000
